export const toPublicNotification = (notification) => ({
  id: notification._id,
  notificationId: notification.notificationId,
  userId: notification.userId,
  title: notification.title,
  message: notification.message,
  type: notification.type,
  priority: notification.priority,
  status: notification.status,
  channel: notification.channel,
  metadata: notification.metadata || {},
  readAt: notification.readAt,
  deliveredAt: notification.deliveredAt,
  deletedAt: notification.deletedAt,
  isRead: Boolean(notification.readAt),
  isUnread: !notification.readAt,
  isNew: notification.createdAt ? Date.now() - new Date(notification.createdAt).getTime() < 24 * 60 * 60 * 1000 : false,
  createdAt: notification.createdAt,
  updatedAt: notification.updatedAt
});
